schema_version: 2
project_name: Littlegreen-Humanoid-Lite
project_version: 2.3.1
task: Velocity-Lilgreen-Stand-ST3215-Loaded-v23
created_at_utc: '2026-07-26T19:56:01Z'
files:
  onnx:
    filename: policy.onnx
    sha256: 66936666934ff02e75681b8ae5c2c6727021df598419016ce0479e8466282608
  yaml:
    filename: policy.yaml
    sha256: 47f1a5aa965335a0d941b11e98793a1ca1c565db79853ff36e347166d3ffe9ed
interface:
  observations: 47
  actions: 12
  action_contract_version: 4
  phase_mode: randomized_static_per_episode
