metadata:
  exported_at: '2026-07-01T20:49:25'
  task: Velocity-Lilgreen-Humanoid-v0
  checkpoint_path: /home/scott/Berkeley-Humanoid-Lite/logs/rsl_rl/humanoid/2026-07-01_20-33-02_resume_seed42_from_15000/model_15999.pt
  export_dir: /home/scott/Berkeley-Humanoid-Lite/logs/rsl_rl/humanoid/2026-07-01_20-33-02_resume_seed42_from_15000/exported
  policy_filename: policy.onnx
  policy_format: onnx
  policy_sha256: a09803aeda3847b46ac0ab8878ee406adaed49e1d8332be5f29496bfb6362088
policy_checkpoint_path: /home/scott/Berkeley-Humanoid-Lite/logs/rsl_rl/humanoid/2026-07-01_20-33-02_resume_seed42_from_15000/exported/policy.onnx
policy_checkpoint_relative_path: policy.onnx
policy_checkpoint_filename: policy.onnx
ip_robot_addr: 127.0.0.1
ip_policy_obs_port: 10000
ip_host_addr: 127.0.0.1
ip_policy_acs_port: 10001
control_dt: 0.04
policy_dt: 0.04
physics_dt: 0.005
num_joints: 14
joints:
- leg_left_hip_roll_joint
- leg_left_hip_yaw_joint
- leg_left_hip_pitch_joint
- leg_left_knee_pitch_joint
- leg_left_ankle_pitch_joint
- leg_left_ankle_roll_joint
- leg_left_toe_pitch_joint
- leg_right_hip_roll_joint
- leg_right_hip_yaw_joint
- leg_right_hip_pitch_joint
- leg_right_knee_pitch_joint
- leg_right_ankle_pitch_joint
- leg_right_ankle_roll_joint
- leg_right_toe_pitch_joint
joint_kp:
- 12.0
- 12.0
- 12.0
- 12.0
- 12.0
- 12.0
- 0.009999999776482582
- 12.0
- 12.0
- 12.0
- 12.0
- 12.0
- 12.0
- 0.009999999776482582
joint_kd:
- 2.0
- 2.0
- 2.0
- 2.0
- 2.0
- 2.0
- 0.05000000074505806
- 2.0
- 2.0
- 2.0
- 2.0
- 2.0
- 2.0
- 0.05000000074505806
effort_limits:
- 6.0
- 6.0
- 6.0
- 6.0
- 6.0
- 6.0
- 9.999999747378752e-05
- 6.0
- 6.0
- 6.0
- 6.0
- 6.0
- 6.0
- 9.999999747378752e-05
default_base_position:
- 0.0
- 0.0
- 0.0
default_joint_positions:
- 0.0
- 0.0
- -0.1
- 0.4
- -0.3
- 0.0
- 0.0
- 0.0
- 0.0
- -0.1
- 0.4
- -0.3
- 0.0
- 0.0
num_observations: 45
history_length: 0
command_velocity:
- -0.2331652045249939
- -0.2243705689907074
- 0.597463846206665
num_actions: 12
action_scale: 0.25
action_indices:
- 0
- 1
- 2
- 3
- 4
- 5
- 7
- 8
- 9
- 10
- 11
- 12
action_limit_lower: -10000
action_limit_upper: 10000
policy_sha256: a09803aeda3847b46ac0ab8878ee406adaed49e1d8332be5f29496bfb6362088
decimation: 8
