#!/usr/bin/env bash
set -euo pipefail

WORKSPACE="${LITTLEGREEN_ROS2_WS:-$HOME/littlegreen_ros2_ws}"
ORT_VERSION="${ONNXRUNTIME_VERSION:-1.22.0}"
ORT_DIR="${ONNXRUNTIME_DIR:-$HOME/libs/onnxruntime-linux-aarch64-${ORT_VERSION}}"
CONFIG_DIR="$HOME/.config/littlegreen"
ENV_FILE="$CONFIG_DIR/ros2_env.sh"
BASHRC="$HOME/.bashrc"
MARKER_BEGIN="# >>> LittleGreen ROS 2 environment >>>"
MARKER_END="# <<< LittleGreen ROS 2 environment <<<"

mkdir -p "$CONFIG_DIR"
cat > "$ENV_FILE" <<EOF_ENV
# Generated by littlegreen_ros2_ws/scripts/configure_environment.sh
# ROS-generated setup files are not guaranteed to support Bash nounset. This
# helper temporarily disables nounset and restores the caller's original state.
_lgh_source_setup_nounset_safe() {
  local setup_file="\$1"
  local nounset_was_on=0
  local source_rc=0

  case "\$-" in
    *u*) nounset_was_on=1; set +u ;;
  esac

  if source "\$setup_file"; then
    source_rc=0
  else
    source_rc=\$?
  fi

  if [[ \$nounset_was_on -eq 1 ]]; then
    set -u
  fi
  return "\$source_rc"
}

if [ -f /opt/ros/humble/setup.bash ]; then
  _lgh_source_setup_nounset_safe /opt/ros/humble/setup.bash
fi
export LITTLEGREEN_ROS2_WS="$WORKSPACE"
export ONNXRUNTIME_DIR="$ORT_DIR"
export LD_LIBRARY_PATH="\$ONNXRUNTIME_DIR/lib:\${LD_LIBRARY_PATH:-}"
if [ -f "\$LITTLEGREEN_ROS2_WS/install/setup.bash" ]; then
  _lgh_source_setup_nounset_safe "\$LITTLEGREEN_ROS2_WS/install/setup.bash"
fi
unset -f _lgh_source_setup_nounset_safe
EOF_ENV

python3 - "$BASHRC" "$ENV_FILE" "$MARKER_BEGIN" "$MARKER_END" <<'PY'
from pathlib import Path
import sys
bashrc = Path(sys.argv[1])
env_file = sys.argv[2]
begin = sys.argv[3]
end = sys.argv[4]
text = bashrc.read_text() if bashrc.exists() else ""
block = f'{begin}\nsource "{env_file}"\n{end}\n'
if begin in text and end in text:
    pre = text.split(begin, 1)[0].rstrip()
    post = text.split(end, 1)[1].lstrip("\n")
    text = pre + "\n\n" + block + ("\n" + post if post else "")
else:
    text = text.rstrip() + "\n\n" + block
bashrc.write_text(text)
PY

echo "Wrote: $ENV_FILE"
echo "Updated: $BASHRC"
echo "Open a new shell, or refresh the current terminal with:"
echo "  source ~/.bashrc"
echo "Directly sourcing $ENV_FILE is equivalent but optional."
